//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_Sysytem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public int IdLibrarian { get; set; }
        public string LiName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string ImgFile { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
