//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_Sysytem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        public int ReaderId { get; set; }
        public string BName { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public Nullable<decimal> ChargesPerDay { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string Department { get; set; }
        public string AssFrom { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> TotalCharges { get; set; }
    }
}
