//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_Sysytem.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isCreated { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> RollNo { get; set; }
        public string Department { get; set; }
        public Nullable<int> AssById { get; set; }
        public string ImgFile { get; set; }
    }
}
